# Generated by Django 5.0.9 on 2025-05-27 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='accounts.user',
        ),
    ]
