# Generated by Django 5.0.9 on 2025-06-02 09:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1, unique=True)),
                ('label', models.ImageField(blank=True, null=True, upload_to='labels/class/')),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.classification',
            },
        ),
        migrations.CreateModel(
            name='EmergencySchedule',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.emergencyschedule',
            },
        ),
        migrations.CreateModel(
            name='EmergencyScheduleImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('emergencyschedule_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/emergencyschedule/')),
            ],
            options={
                'db_table': 'goods.emergencyscheduleimage',
            },
        ),
        migrations.CreateModel(
            name='ExceptedQuantities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=2, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.exceptedquantities',
            },
        ),
        migrations.CreateModel(
            name='ExceptedQuantitiesImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('exceptedquantities_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/exceptedquantities/')),
            ],
            options={
                'db_table': 'goods.exceptedquantitiesimage',
            },
        ),
        migrations.CreateModel(
            name='IBCInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.ibcinstructions',
            },
        ),
        migrations.CreateModel(
            name='IBCInstructionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ibcinstructions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/ibcinstructions/')),
            ],
            options={
                'db_table': 'goods.ibcinstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='IBCProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.ibcprovisions',
            },
        ),
        migrations.CreateModel(
            name='IBCProvisionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ibcprovisions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/ibcprovisions/')),
            ],
            options={
                'db_table': 'goods.ibcprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='PackingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.packinggroup',
            },
        ),
        migrations.CreateModel(
            name='PackingGroupImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packinggroup_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/packinggroup/')),
            ],
            options={
                'db_table': 'goods.packinggroupimage',
            },
        ),
        migrations.CreateModel(
            name='PackingInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.packinginstructions',
            },
        ),
        migrations.CreateModel(
            name='PackingInstructionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packinginstructions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/packinginstructions/')),
            ],
            options={
                'db_table': 'goods.packinginstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='PackingProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.packingprovisions',
            },
        ),
        migrations.CreateModel(
            name='PackingProvisionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('packingprovisions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/packingprovisions/')),
            ],
            options={
                'db_table': 'goods.packingprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='Segregation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.segregation',
            },
        ),
        migrations.CreateModel(
            name='SegregationImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('segregation_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/segregation/')),
            ],
            options={
                'db_table': 'goods.segregationimage',
            },
        ),
        migrations.CreateModel(
            name='SpecialProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=3, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.specialprovisions',
            },
        ),
        migrations.CreateModel(
            name='SpecialProvisionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('specialprovisions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/specialprovisions/')),
            ],
            options={
                'db_table': 'goods.specialprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='StowageHandling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.stowagehandling',
            },
        ),
        migrations.CreateModel(
            name='StowageHandlingImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stowagehandling_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/stowagehandling/')),
            ],
            options={
                'db_table': 'goods.stowagehandlingimage',
            },
        ),
        migrations.CreateModel(
            name='TankInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.tankinstructions',
            },
        ),
        migrations.CreateModel(
            name='TankInstructionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tankinstructions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/tankinstructions/')),
            ],
            options={
                'db_table': 'goods.tankinstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='TankProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.tankprovisions',
            },
        ),
        migrations.CreateModel(
            name='TankProvisionsImage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tankprovisions_code', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/tankprovisions/')),
            ],
            options={
                'db_table': 'goods.tankprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='UNCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4, unique=True)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'goods.uncode',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('label', models.ImageField(blank=True, null=True, upload_to='labels/division/')),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='goods.classification')),
            ],
            options={
                'db_table': 'goods.division',
            },
        ),
        migrations.CreateModel(
            name='CompatibilityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('description', models.JSONField(default=dict)),
                ('activate', models.BooleanField(default=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_groups', to='goods.division')),
            ],
            options={
                'db_table': 'goods.compatibilitygroup',
            },
        ),
        migrations.CreateModel(
            name='ClassDivisionGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('activate', models.BooleanField(default=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_divisions', to='goods.classification')),
                ('compatibility_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_divisions', to='goods.compatibilitygroup')),
                ('division', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='class_divisions', to='goods.division')),
            ],
            options={
                'db_table': 'goods.class_division_group',
            },
        ),
        migrations.CreateModel(
            name='SegregationBar',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('segregationlevel', models.SmallIntegerField(default=0)),
                ('activate', models.BooleanField(default=True)),
                ('fromclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segregationbars_from', to='goods.classdivisiongroup')),
                ('toclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segregationbars_to', to='goods.classdivisiongroup')),
            ],
            options={
                'db_table': 'goods.segregationbar',
            },
        ),
        migrations.CreateModel(
            name='DangerousGoods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('propershippingname', models.TextField(blank=True, null=True)),
                ('limitedquantities', models.CharField(blank=True, max_length=100, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('classdivision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dangerousgoods', to='goods.classdivisiongroup')),
                ('subsidiaryhazards', models.ManyToManyField(blank=True, related_name='dangerousgoods_subsidiaryhazards', to='goods.classdivisiongroup')),
                ('emergencyschedule', models.ManyToManyField(blank=True, related_name='dangerousgoods_emergencyschedule', to='goods.emergencyschedule')),
                ('exceptedquantities', models.ManyToManyField(blank=True, related_name='dangerousgoods_exceptedquantities', to='goods.exceptedquantities')),
                ('ibcinstructions', models.ManyToManyField(blank=True, related_name='dangerousgoods_ibcinstructions', to='goods.ibcinstructions')),
                ('ibcprovisions', models.ManyToManyField(blank=True, related_name='dangerousgoods_ibcprovisions', to='goods.ibcprovisions')),
                ('packinggroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dangerousgoods', to='goods.packinggroup')),
                ('packinginstructions', models.ManyToManyField(blank=True, related_name='dangerousgoods_packinginstructions', to='goods.packinginstructions')),
                ('packingprovisions', models.ManyToManyField(blank=True, related_name='dangerousgoods_packingprovisions', to='goods.packingprovisions')),
                ('segregation', models.ManyToManyField(blank=True, related_name='dangerousgoods_segregation', to='goods.segregation')),
                ('specialprovisions', models.ManyToManyField(blank=True, related_name='dangerousgoods_specialprovisions', to='goods.specialprovisions')),
                ('stowagehandling', models.ManyToManyField(blank=True, related_name='dangerousgoods_stowagehandling', to='goods.stowagehandling')),
                ('tankinstructions', models.ManyToManyField(blank=True, related_name='dangerousgoods_tankinstructions', to='goods.tankinstructions')),
                ('tankprovisions', models.ManyToManyField(blank=True, related_name='dangerousgoods_tankprovisions', to='goods.tankprovisions')),
                ('uncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangerousgoods', to='goods.uncode')),
            ],
            options={
                'db_table': 'goods.dangerousgoods',
            },
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('classification', 'code'), name='unique_class_code'),
        ),
        migrations.AddConstraint(
            model_name='compatibilitygroup',
            constraint=models.UniqueConstraint(fields=('division', 'code'), name='unique_division_code'),
        ),
        migrations.AddConstraint(
            model_name='classdivisiongroup',
            constraint=models.UniqueConstraint(fields=('classification', 'division', 'compatibility_group'), name='unique_class_division_group'),
        ),
        migrations.AddConstraint(
            model_name='segregationbar',
            constraint=models.UniqueConstraint(fields=('fromclass', 'toclass'), name='unique_from_to_class'),
        ),
        migrations.AddConstraint(
            model_name='dangerousgoods',
            constraint=models.UniqueConstraint(fields=('uncode', 'classdivision', 'packinggroup'), name='unique_un_division_packing'),
        ),
    ]
