# Generated by Django 5.0.9 on 2025-05-02 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dangerousgoods',
            name='activate',
        ),
    ]
