# Generated by Django 5.0.9 on 2025-06-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emergencyscheduleimage',
            old_name='emergencyschedule_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='exceptedquantitiesimage',
            old_name='exceptedquantities_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='ibcinstructionsimage',
            old_name='ibcinstructions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='ibcprovisionsimage',
            old_name='ibcprovisions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='packinggroupimage',
            old_name='packinggroup_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='packinginstructionsimage',
            old_name='packinginstructions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='packingprovisionsimage',
            old_name='packingprovisions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='segregationimage',
            old_name='segregation_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='specialprovisionsimage',
            old_name='specialprovisions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='stowagehandlingimage',
            old_name='stowagehandling_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='tankinstructionsimage',
            old_name='tankinstructions_code',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='tankprovisionsimage',
            old_name='tankprovisions_code',
            new_name='code',
        ),
    ]
