# Generated by Django 5.0.9 on 2025-04-30 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='uncode',
            table='goods.uncode',
        ),
    ]
