# Generated by Django 5.0.9 on 2025-05-27 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_dangerousgoods_activate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stowagehandling',
            name='code',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
