# Generated by Django 5.0.9 on 2025-05-01 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_classdivisiongroup_id_alter_classification_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='packinginstructions',
            name='is_activate',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='classification',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='compatibilitygroup',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='division',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='emergencyschedule',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='exceptedquantities',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ibcinstructions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='ibcprovisions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packinggroup',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packinginstructions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='packingprovisions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='segregation',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='specialprovisions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='stowagehandling',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tankinstructions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='tankprovisions',
            name='description',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='uncode',
            name='description',
            field=models.JSONField(default=dict),
        ),
    ]
