# Generated by Django 5.0.9 on 2025-05-29 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_alter_stowagehandling_code'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='compatibilitygroup',
            name='unique_class_division_code',
        ),
        migrations.RemoveField(
            model_name='compatibilitygroup',
            name='classification',
        ),
        migrations.AddConstraint(
            model_name='compatibilitygroup',
            constraint=models.UniqueConstraint(fields=('division', 'code'), name='unique_division_code'),
        ),
    ]
