# Generated by Django 5.0.9 on 2025-05-30 04:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_remove_compatibilitygroup_unique_class_division_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyScheduleImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/emergencyschedule/')),
                ('emergencyschedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.emergencyschedule')),
            ],
            options={
                'db_table': 'goods.emergencyscheduleimage',
            },
        ),
        migrations.CreateModel(
            name='ExceptedQuantitiesImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/exceptedquantities/')),
                ('exceptedquantities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.exceptedquantities')),
            ],
            options={
                'db_table': 'goods.exceptedquantitiesimage',
            },
        ),
        migrations.CreateModel(
            name='IBCInstructionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ibcinstructions/')),
                ('ibcinstructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.ibcinstructions')),
            ],
            options={
                'db_table': 'goods.ibcinstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='IBCProvisionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/ibcprovisions/')),
                ('ibcprovisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.ibcprovisions')),
            ],
            options={
                'db_table': 'goods.ibcprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='PackingGroupImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/packinggroup/')),
                ('packinggroup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.packinggroup')),
            ],
            options={
                'db_table': 'goods.packinggroupimage',
            },
        ),
        migrations.CreateModel(
            name='PackingInstructionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/packinginstructions/')),
                ('packinginstructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.packinginstructions')),
            ],
            options={
                'db_table': 'goods.packinginstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='PackingProvisionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/packingprovisions/')),
                ('packingprovisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.packingprovisions')),
            ],
            options={
                'db_table': 'goods.packingprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='SegregationImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/segregation/')),
                ('segregation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.segregation')),
            ],
            options={
                'db_table': 'goods.segregationimage',
            },
        ),
        migrations.CreateModel(
            name='SpecialProvisionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/specialprovisions/')),
                ('specialprovisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.specialprovisions')),
            ],
            options={
                'db_table': 'goods.specialprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='StowageHandlingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/stowagehandling/')),
                ('stowagehandling', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.stowagehandling')),
            ],
            options={
                'db_table': 'goods.stowagehandlingimage',
            },
        ),
        migrations.CreateModel(
            name='TankInstructionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/tankinstructions/')),
                ('tankinstructions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.tankinstructions')),
            ],
            options={
                'db_table': 'goods.tankinstructionsimage',
            },
        ),
        migrations.CreateModel(
            name='TankProvisionsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/tankprovisions/')),
                ('tankprovisions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.tankprovisions')),
            ],
            options={
                'db_table': 'goods.tankprovisionsimage',
            },
        ),
        migrations.CreateModel(
            name='UNCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/uncode/')),
                ('uncode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='goods.uncode')),
            ],
            options={
                'db_table': 'goods.uncodeimage',
            },
        ),
    ]
