# Generated by Django 5.0.9 on 2025-05-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_packinginstructions_is_activate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dangerousgoods',
            name='proper_shipping_name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
