# Generated by Django 5.0.9 on 2025-06-05 16:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('label', models.ImageField(blank=True, null=True, upload_to='labels/class/')),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'imdg.classification',
            },
        ),
        migrations.CreateModel(
            name='IMDGAmendment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='documents/imdg/amendments/')),
                ('pages_directory_path', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('upload_at', models.DateTimeField(auto_now_add=True)),
                ('is_effective', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'imdg.imdgamendment',
                'ordering': ['-upload_at'],
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('label', models.ImageField(blank=True, null=True, upload_to='labels/division/')),
                ('description', models.TextField(blank=True, null=True)),
                ('classification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='imdg.classification')),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divisions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.division',
            },
        ),
        migrations.CreateModel(
            name='IBCProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibc_provisions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.ibcprovisions',
            },
        ),
        migrations.CreateModel(
            name='IBCInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ibc_instructions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.ibcinstructions',
            },
        ),
        migrations.CreateModel(
            name='ExceptedQuantities',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excepted_quantities', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.exceptedquantities',
            },
        ),
        migrations.CreateModel(
            name='EmergencySchedules',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_schedules', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.emergencyschedules',
            },
        ),
        migrations.CreateModel(
            name='DangerousGoods',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('un_code', models.CharField(max_length=4)),
                ('proper_shipping_name', models.TextField(blank=True, null=True)),
                ('class_division_code', models.CharField(blank=True, max_length=4, null=True)),
                ('subsidiary_hazards_codes', models.JSONField(blank=True, null=True)),
                ('packing_group_code', models.CharField(blank=True, max_length=3, null=True)),
                ('special_provisions_codes', models.JSONField(blank=True, null=True)),
                ('limited_quantities', models.TextField(blank=True, null=True)),
                ('excepted_quantities_codes', models.JSONField(blank=True, null=True)),
                ('packing_instructions_codes', models.JSONField(blank=True, null=True)),
                ('packing_provisions_codes', models.JSONField(blank=True, null=True)),
                ('ibc_instructions_codes', models.JSONField(blank=True, null=True)),
                ('ibc_provisions_codes', models.JSONField(blank=True, null=True)),
                ('tank_instructions_codes', models.JSONField(blank=True, null=True)),
                ('tank_provisions_codes', models.JSONField(blank=True, null=True)),
                ('emergency_schedules_codes', models.JSONField(blank=True, null=True)),
                ('stowage_handling_codes', models.JSONField(blank=True, null=True)),
                ('segregation_codes', models.JSONField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dangerousgoods', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.dangerousgoods',
            },
        ),
        migrations.CreateModel(
            name='CompatibilityGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_groups', to='imdg.division')),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibility_groups', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.compatibilitygroup',
            },
        ),
        migrations.AddField(
            model_name='classification',
            name='imdgamendment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classifications', to='imdg.imdgamendment'),
        ),
        migrations.CreateModel(
            name='PackingGroup',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_groups', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.packinggroup',
            },
        ),
        migrations.CreateModel(
            name='PackingInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_instructions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.packinginstructions',
            },
        ),
        migrations.CreateModel(
            name='PackingProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packing_provisions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.packingprovisions',
            },
        ),
        migrations.CreateModel(
            name='Segregation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segregations', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.segregation',
            },
        ),
        migrations.CreateModel(
            name='SpecialProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_provisions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.specialprovisions',
            },
        ),
        migrations.CreateModel(
            name='StowageHandling',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stowage_handlings', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.stowagehandling',
            },
        ),
        migrations.CreateModel(
            name='TankInstructions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_instructions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.tankinstructions',
            },
        ),
        migrations.CreateModel(
            name='TankProvisions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=10)),
                ('pdf_regions', models.JSONField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_provisions', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.tankprovisions',
            },
        ),
        migrations.CreateModel(
            name='UNCode',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=4)),
                ('description', models.TextField(blank=True, null=True)),
                ('imdgamendment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uncodes', to='imdg.imdgamendment')),
            ],
            options={
                'db_table': 'imdg.uncode',
            },
        ),
        migrations.AddConstraint(
            model_name='ibcprovisions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_ibcprovisioncode'),
        ),
        migrations.AddConstraint(
            model_name='ibcinstructions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_ibcinstructioncode'),
        ),
        migrations.AddConstraint(
            model_name='exceptedquantities',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_exceptedquantitiecode'),
        ),
        migrations.AddConstraint(
            model_name='emergencyschedules',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_emergencyschedulecode'),
        ),
        migrations.AddConstraint(
            model_name='division',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'classification', 'code'), name='unique_imdgamendment_classification_divisioncode'),
        ),
        migrations.AddConstraint(
            model_name='compatibilitygroup',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'division', 'code'), name='unique_imdgamendment_division_compatibilitygroupcode'),
        ),
        migrations.AddConstraint(
            model_name='classification',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_classificationcode'),
        ),
        migrations.AddConstraint(
            model_name='packinggroup',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_packinggroupcode'),
        ),
        migrations.AddConstraint(
            model_name='packinginstructions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_packinginstructioncode'),
        ),
        migrations.AddConstraint(
            model_name='packingprovisions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_packingprovisioncode'),
        ),
        migrations.AddConstraint(
            model_name='segregation',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_segregationcode'),
        ),
        migrations.AddConstraint(
            model_name='specialprovisions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_specialprovisioncode'),
        ),
        migrations.AddConstraint(
            model_name='stowagehandling',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_stowagehandlingcode'),
        ),
        migrations.AddConstraint(
            model_name='tankinstructions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_tankinstructioncode'),
        ),
        migrations.AddConstraint(
            model_name='tankprovisions',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_tankprovisioncode'),
        ),
        migrations.AddConstraint(
            model_name='uncode',
            constraint=models.UniqueConstraint(fields=('imdgamendment', 'code'), name='unique_imdgamendment_uncode'),
        ),
    ]
