# Generated by Django 5.0.9 on 2025-06-08 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdg', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='segregationrule',
            table='imdg.segregationrule',
        ),
    ]
