name: CI/CD Pipeline for Dangerous Goods Service

on:
  push:
    branches: [ "main" ]

env:
  IMAGE_NAME: ghcr.io/skynguyen313/dangerous-goods-service

jobs:

  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16.9
        env:
          POSTGRES_DB: test_db
          POSTGRES_USER: test_user
          POSTGRES_PASSWORD: test_password
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U test_user -d test_db"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Cache Pip dependencies
      uses: actions/cache@v4
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Check Docker Compose version
      run: docker compose version

    - name: Create .env file for testing
      run: |
        echo "POSTGRES_DB=test_db" >> .env
        echo "POSTGRES_USER=test_user" >> .env
        echo "POSTGRES_PASSWORD=test_password" >> .env
        echo "POSTGRES_HOST=localhost" >> .env
        echo "POSTGRES_PORT=5432" >> .env

    - name: Build Docker containers
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml build

    - name: Run Django tests
      run: docker compose -f docker-compose.yml -f docker-compose.ci.yml run --rm web python manage.py test

  build_and_push:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: |
          ${{ env.IMAGE_NAME }}:latest
          ${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push

    steps:
    - name: Deploy to server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          # Move to the project folder on the server
          cd ${{ vars.DEPLOY_PATH }}
          
          # Pull latest code from main branch
          git pull origin main
          
          # Log in to GitHub Container Registry
          echo ${{ secrets.DOCKER_PASSWORD }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          
          # Pull latest image
          docker compose pull
          
          # Restart containers
          docker compose up -d

          # Clean up unused images
          docker image prune -af

    - name: Send Email Notification
      if: always()
      uses: dawidd6/action-send-mail@v3
      with:
        server_address: ${{ secrets.SMTP_SERVER }}
        server_port: ${{ secrets.SMTP_PORT }}
        username: ${{ secrets.SMTP_USERNAME }}
        password: ${{ secrets.SMTP_PASSWORD }}
        subject: "GitHub Actions: Deployment ${{ job.status }}"
        body: "Build job in ${{ github.repository }} has ${{ job.status }}."
        to: "skynguyen313@gmail.com"
        from: CI/CD Bot Dangerous Goods Service<skynguyen313@gmail.com>
